"""initial: accounts_table and reservations

Revision ID: bb76c3d49a86
Revises: 
Create Date: 2026-05-12 00:45:28.774179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb76c3d49a86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cid', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_table_account_number'), 'accounts_table', ['account_number'], unique=True)
    op.create_index(op.f('ix_accounts_table_cid'), 'accounts_table', ['cid'], unique=False)
    op.create_index(op.f('ix_accounts_table_phone'), 'accounts_table', ['phone'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('pickup_time', sa.Time(), nullable=False),
    sa.Column('pickup_address', sa.String(length=512), nullable=False),
    sa.Column('drop_off_address', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_account_id'), 'reservations', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_account_id'), table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_accounts_table_phone'), table_name='accounts_table')
    op.drop_index(op.f('ix_accounts_table_cid'), table_name='accounts_table')
    op.drop_index(op.f('ix_accounts_table_account_number'), table_name='accounts_table')
    op.drop_table('accounts_table')
    # ### end Alembic commands ###
